variable "rg-name" {}
variable "loc-name" {}
variable "vnet-name" {}
variable "add-name" {}
variable "sub-name" {}
variable "ip-name" {}
variable "pip-name" {}
variable "all-name" {}
variable "nic-name1" {}
variable "nic-name2" {}
variable "pipall-name" {}
variable "nsg-name" {}
variable "sec-name" {}
variable "value" {}
variable "dic-name" {}
variable "acc-name" {}
variable "pt-name" {}
variable "sport-name" {}
variable "dport-name" {}
variable "sadd-name" {}
variable "dadd-name" {}
variable "vm-name" {}
variable "vm-name2" {}
variable "size-name" {}
variable "disk-name" {}
variable "cac-name" {}
variable "sactype-name" {}
variable "pub-name" {}
variable "machine-name" {}
variable "sku-name" {}
variable "ver-name" {}
variable "computer_name" {}
variable "admin-name" {}
variable "admin-pass" {}
variable "disk-name2" {}
variable "pip-name1" {}
variable "alb-name" {}
variable"fip-name"{}
variable "acc-tier" {}
variable "ar-type" {}
variable "acc-type" {}

